#!/bin/bash

# Source the environment file to access its variables
source orderApp.env

# Run the generate command (Replace 'generate' with the actual command to generate your files)
npm run generate

# Local build output directory (generated by "npm run generate" or your actual command)
LOCAL_BUILD_DIR=".output/public"

# Deploy files to the remote server using scp
echo "Copying files to the remote server..."
scp -r "$LOCAL_BUILD_DIR" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DEPLOY_DIR"

echo "Deployment complete!"
